### ISSUE TITLE
upload接口报错412 Client Error

### ISSUE THREAD

**Issue by Naccl** [SocialSisterYi/bcut-asr#12]
https://github.com/SocialSisterYi/bcut-asr/blob/1a2810759bb0b6b4707125c61b30c1bfaff24296/bcut_asr/__init__.py#L213-L227

227行报错
```
requests.exceptions.HTTPError: 412 Client Error: Precondition Failed for url: https://member.bilibili.com/x/bcut/rubick-interface/resource/create
```

是不是寄了

**Comment by duffercn** [comment]
命令行执行一样：
requests.exceptions.HTTPError: 412 Client Error: Precondition Failed for url: https://member.bilibili.com/x/bcut/rubick-interface/resource/create

隐隐不好的感觉

**Comment by ambitiousCC** [comment]
大概率官方接口寄了

**Comment by Jiangxiaonan1** [comment]
有替换的接口吗

**Comment by Jiangxiaonan1** [comment]
raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 412 Client Error: Precondition Failed for url: https://member.bilibili.com/x/bcut/rubick-interface/resource/create

**Comment by cf1998** [comment]
我也遇到了，添加个请求头就解决了

headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36",
    "Cache-Control": "no-cache"
}

**Comment by luoying-zero** [comment]
> 我也遇到了，添加个请求头就解决了
> 
> headers = { "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36", "Cache-Control": "no-cache" }

解决了😇

**Comment by L-Chris** [comment]
现在报错
{
  code: -400,
  message: "Key: 'CreateResourceReq.ResourceFileType' Error:Field validation for 'ResourceFileType' failed on the 'required' tag",
  ttl: 1
}
你们遇到过吗？

**Comment by macleo** [comment]
bcut-asr fangqi.mp3
2025-08-10 17:18:05,191 - [INFO] 加载文件成功: 1754817485.mp3
Traceback (most recent call last):
  File "/opt/anaconda3/envs/py310/bin/bcut-asr", line 8, in <module>
    sys.exit(main())
  File "/opt/anaconda3/envs/py310/lib/python3.10/site-packages/bcut_asr/__main__.py", line 114, in main
    asr.upload()
  File "/opt/anaconda3/envs/py310/lib/python3.10/site-packages/bcut_asr/__init__.py", line 227, in upload
    resp.raise_for_status()
  File "/opt/anaconda3/envs/py310/lib/python3.10/site-packages/requests/models.py", line 1026, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 412 Client Error: Precondition Failed for url: https://member.bilibili.com/x/bcut/rubick-interface/resource/create

**Comment by luoying-zero** [comment]
现在又报错了，可能接口又变了:
```
2025-11-10 11:44:15,775 - [INFO] 分片1上传成功: afb64a7af11343b53b29d5d2c390235f
2025-11-10 11:44:15,828 - [INFO] 提交成功
2025-11-10 11:44:15,914 - [INFO] 任务已创建: 63bcd90bbfee44e484969a8581d77713
Traceback (most recent call last):
  File "bcut_asr.py", line 2, in <module>
  File "bcut_asr\__main__.py", line 116, in main
  File "bcut_asr\__init__.py", line 310, in result
  File "pydantic\main.py", line 705, in model_validate
pydantic_core._pydantic_core.ValidationError: 1 validation error for ResultRspSchema
result
  Field required [type=missing, input_value={'task_id': '63bcd90bbfee...remark': '', 'state': 1}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.11/v/missing
[PYI-5516:ERROR] Failed to execute script 'bcut_asr' due to unhandled exception!
```
