### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by freemedom** [SocialSisterYi/bcut-asr#2]
`
Traceback (most recent call last):
  File "C:\Users\\AppData\Local\Programs\Python\Python39\Scripts\bcut_asr-script.py", line 33, in <module>
    sys.exit(load_entry_point('bcut-asr==0.0.2', 'console_scripts', 'bcut_asr')())
  File "C:\Users\\AppData\Local\Programs\Python\Python39\Scripts\bcut_asr-script.py", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "C:\Users\\AppData\Local\Programs\Python\Python39\lib\importlib\metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "C:\Users\\AppData\Local\Programs\Python\Python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "C:\Users\\AppData\Local\Programs\Python\Python39\lib\site-packages\bcut_asr-0.0.2-py3.9.egg\bcut_asr\__init__.py", line 28, in <module>
  File "C:\Users\\AppData\Local\Programs\Python\Python39\lib\site-packages\bcut_asr-0.0.2-py3.9.egg\bcut_asr\__init__.py", line 44, in BcutASR
TypeError: unsupported operand type(s) for |: 'type' and 'ABCMeta'
`

**Comment by freemedom** [comment]
Traceback (most recent call last):
  File "C:\Users\\AppData\Local\Programs\Python\Python39\Scripts\bcut_asr-script.py", line 33, in <module>
    sys.exit(load_entry_point('bcut-asr==0.0.2', 'console_scripts', 'bcut_asr')())
  File "C:\Users\\AppData\Local\Programs\Python\Python39\Scripts\bcut_asr-script.py", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "C:\Users\\AppData\Local\Programs\Python\Python39\lib\importlib\metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "C:\Users\\AppData\Local\Programs\Python\Python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "C:\Users\\AppData\Local\Programs\Python\Python39\lib\site-packages\bcut_asr-0.0.2-py3.9.egg\bcut_asr\__init__.py", line 28, in <module>
  File "C:\Users\\AppData\Local\Programs\Python\Python39\lib\site-packages\bcut_asr-0.0.2-py3.9.egg\bcut_asr\__init__.py", line 44, in BcutASR
TypeError: unsupported operand type(s) for |: 'type' and 'ABCMeta'

**Comment by cxumol** [comment]
it's only compatible on python 3.10+
I made a fork working on python 3.9 https://github.com/cxu-fork/bcut-asr

**Comment by freemedom** [comment]
@cxumol  Thank you.
